palette = "tokyonight"

format = """
$character\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang"""

add_newline = false

[character]
success_symbol = "[➜](bold success)"  # light-green
error_symbol = "[➜](bold error)"    # red

[directory]
truncation_length = 1
read_only = " 🔒"
style = "directory"                     # yellow

[git_branch]
symbol = "git"
format = '[$symbol:\([$branch](bold branch)\)](bold symbol) '
[git_status]
style = "bold status"               # orange

[python]
format = "[ $virtualenv]($style) "
style = "python"                    # comment

[nodejs]
symbol = ""
format = "[$symbol]($style) "
style = "node"                    # green

[rust]
symbol = ""
format = "[$symbol]($style) "
style = "rust"                    # orange

[golang]
symbol = ""
format = "[$symbol]($style) "
style = "go"

[palettes.tokyonight]
error = "#f7768e"                  # red
success = "#9ece6a"                # light green
directory = "#2ac3de"              # aqua
branch = "#f7768e"                 # red
symbol = "#7dcfff"                 # cyan git:( )
status = "#9d7cd8"                 # purple
python = "#565f89"                 # comment
node = "#73daca"                   # green
rust = "#ff9e64"                   # orange
go = "#7aa2f7"                     # blue

[palettes.gruvbox]
error = "#fb4934"
success = "#b8bb26"
directory = "#73daca"
branch = "#fb4934"
symbol = "#83a598"
status = "#928374"
python = "#fabd2f"
node = "#83a598"
rust = "#fe8019"
go = "#83a598"

[palettes.kanagawa]
error = "#E46876"
success = "#98BB6C"
directory = "#7FB4CA"              # aqua
branch = "#E46876"                 # red
symbol = "#7FB4CA"                 # cyan git:( )
status = "#54546D"                 # purple
python = "#DCA561"                 # comment
node = "#98BB6C"                   # green
rust = "#DCA561"                   # orange
go = "#7FB4CA"                     # blue

[palettes.catppuccin_mocha]
error = "#F38BA8"
success = "#A6E3A1"
directory = "#89B4FA"              # aqua
branch = "#F38BA8"                 # red
symbol = "#89B4FA"                 # cyan git:( )
status = "#9399B2"                 # purple
python = "#F9E2AF"                 # comment
node = "#A6E3A1"                   # green
rust = "F9E2AF"                   # orange
go = "#89B4FA"                     # blue

# Tokyonight Storm Colours
# red = "#f7768e"
# orange = "#ff9e64"
# yellow = "#e0af68"
# light-green = "#9ece6a"
# green = "#73daca"
# aqua = "#2ac3de"
# teal = "#1abc9c"
# turquoise = "#89ddff"
# light-cyan = "#b4f9f8"
# cyan = "#7dcfff"
# blue = "#7aa2f7"
# purple = "#9d7cd8"
# magenta = "#bb9af7"
# comment = "#565f89"
# black = "#414868"

# Gruvbox Colours
# red = "#fb4934"
# orange = "#fe8019"
# yellow = "#fabd2f"
# light-green = "#b8bb26"
# green = "#83a598"       # mapped to git branch label blue-ish
# aqua = "#73daca"        # fallback from original greenish
# cyan = "#83a598"        # reused git branch label blue-ish
# blue = "#83a598"
# purple = "#928374"      # using gray for purple (closest)
# magenta = "#928374"     # also gray-ish fallback
# comment = "#928374"
# black = "#282828"       # gruvbox black

# Kanagawa Colours
# red = "#E46876"
# orange = "#DCA561"      # used for git_status
# yellow = "#DCA561"
# light-green = "#98BB6C"
# green = "#7FB4CA"       # mapped blue-ish
# aqua = "#7FB4CA"
# cyan = "#7FB4CA"
# blue = "#7FB4CA"
# purple = "#54546D"      # muted gray-purple
# magenta = "#54546D"
# comment = "#54546D"
# black = "#16161e"       # kanagawa black background

# Catppuccin Mocha Colours
# red = "#f38ba8"
# orange = "#f9e2af"      # used for git_status (yellow-ish)
# yellow = "#f9e2af"
# light-green = "#a6e3a1"
# green = "#89b4fa"       # used as git branch label (blue-ish)
# aqua = "#89b4fa"
# cyan = "#89b4fa"
# blue = "#89b4fa"
# purple = "#9399b2"      # subtle gray-purple
# magenta = "#9399b2"
# comment = "#565f89"
# black = "#16161e"

