[flavor]
light = "catppucin-mocha"
dark = "catppuccin-moch"
# use = "catppuccin-mocka"
# dark = "tokyo-night"
# dark = "gruvbox-dark"
use = "kanagawa"
# dark = "kanagawa"
# use = "vscode-dark-plus"
# dark = "ashen"
# dark = "ayu-dark"
