theme = "theme"

[editor]
true-color = true
undercurl = true
color-modes = true
popup-border = "all"
line-number = "relative"
cursorline = true
auto-completion = true
auto-format = true
text-width = 80
rulers = [80]
indent-heuristic = "tree-sitter"

[editor.smart-tab]
enable = true

[editor.inline-diagnostics]
cursor-line = "info"
other-lines = "warning"
max-wrap = 20
max-diagnostics = 10

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1
character = "▏"  #"╎" # "▏", "┆", "┊"

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.soft-wrap]
enable = true
wrap-indicator = "↩ "

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"S-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"S-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
G="goto_file_end"
"{" = ["goto_next_paragraph"]
"}" = ["goto_prev_paragraph"]
 "*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
 C-g = [
    ":write-all", 
    ":new", 
    ":insert-output lazygit", 
    ":set mouse false", # First disable mouse to hint helix into activating it
    ":set mouse true",
    ":buffer-close!", 
    ":redraw", 
    ":reload-all"
]

[keys.normal.space]
q = ":quit"
w = ":write"
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]

# togglers
[keys.normal.space.t]
i = ":toggle lsp.display-inlay-hints"

[keys.select]
"{" = ["goto_next_paragraph"]
"}" = ["goto_prev_paragraph"]
