 # Catppuccin Mocha
 # gui:
 #   theme:
 #     activeBorderColor:
 #       - '#f5e0dc'
 #       - bold
 #     inactiveBorderColor:
 #       - '#a6adc8'
 #     optionsTextColor:
 #       - '#89b4fa'
 #     selectedLineBgColor:
 #       - '#313244'
 #     cherryPickedCommitBgColor:
 #       - '#45475a'
 #     cherryPickedCommitFgColor:
 #       - '#f5e0dc'
 #     unstagedChangesColor:
 #       - '#f38ba8'
 #     defaultFgColor:
 #       - '#cdd6f4'
 #     searchingActiveBorderColor:
 #       - '#f9e2af'

 #   authorColors:
 #     '*': '#b4befe'

 # Ayu Mirage
# gui
  # theme:
  #   activeBorderColor:
  #     - '#FFD173'
  #     - bold
  #   inactiveBorderColor:
  #     - '#B8CFE6'
  #   optionsTextColor:
  #     - '#FFDFB3'
  #   selectedLineBgColor:
  #     - '#637599'
  #   cherryPickedCommitBgColor:
  #     - '#B8CFE6'
  #   cherryPickedCommitFgColor:
  #     - '#FFD173'
  #   unstagedChangesColor:
  #     - '#95E6CB'
  #   defaultFgColor:
  #     - '#CCCAC2'
  #   searchingActiveBorderColor:
  #     - '#F28779'
  # authorColors:
  #   '*': '#80BFFF'

  # Ashen Theme
# Author: Daniel Fichtinger
# License: MIT
# gui:
#   authorColors:
#     # Recommended: Set your own name to this color!
#     # "Daniel Fichtinger": "#E49A44"
#     "*": "#B14242"
#   theme:
#     # Border color of focused window
#     activeBorderColor:
#       - "#B14242"

#     # Border color of non-focused windows
#     inactiveBorderColor:
#       - "#a7a7a7"

#     # Border color of focused window when searching in that window
#     searchingActiveBorderColor:
#       - "#4A8B8B"
#       - bold

#     # Color of keybindings help text in the bottom line
#     optionsTextColor:
#       - "#B14242"

#     # Background color of selected line.
#     # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
#     selectedLineBgColor:
#       - "#323232"

#     # Background color of selected line when view doesn't have focus.
#     inactiveViewSelectedLineBgColor:
#       - bold

#     # Foreground color of copied commit
#     cherryPickedCommitFgColor:
#       - "#191919"

#     # Background color of copied commit
#     cherryPickedCommitBgColor:
#       - "#4A8B8B"

#     # Foreground color of marked base commit (for rebase)
#     markedBaseCommitFgColor:
#       - "#d5d5d5"

#     # Background color of marked base commit (for rebase)
#     markedBaseCommitBgColor:
#       - "#191919"

#     # Color for file with unstaged changes
#     unstagedChangesColor:
#       - "#B14242"

#     # Default text color
#     defaultFgColor:
#       - "#d5d5d5"

# vscode dark
gui:
  theme:
    activeBorderColor:
      - '#7E9CD8'          # Blue for active borders (Light Blue)
      - bold
    inactiveBorderColor:
      - '#6B85A0'          # Muted Blue for inactive borders
    optionsTextColor:
      - '#7AA89F'          # Cyan for help text (Commands)
    selectedLineBgColor:
      - '#2D4F67'          # Muted Blue (Selection)
    cherryPickedCommitBgColor:
      - '#957FB8'          # Soft Purple (Cherry-picked commits)
    cherryPickedCommitFgColor:
      - '#DCD7BA'          # Foreground (Soft Beige)
    unstagedChangesColor:
      - '#C34043'          # Muted Red (Unstaged Changes)
    defaultFgColor:
      - '#DCD7BA'          # Foreground color (Soft Beige)
    searchingActiveBorderColor:
      - '#FF9E64'          # Bright Orange for search borders
  authorColors:
    '*': '#76946A'          # Subtle Green (Authors)

