 # Catppuccin Mocha
 gui:
   theme:
     activeBorderColor:
       - '#f5e0dc'
       - bold
     inactiveBorderColor:
       - '#a6adc8'
     optionsTextColor:
       - '#89b4fa'
     selectedLineBgColor:
       - '#313244'
     cherryPickedCommitBgColor:
       - '#45475a'
     cherryPickedCommitFgColor:
       - '#f5e0dc'
     unstagedChangesColor:
       - '#f38ba8'
     defaultFgColor:
       - '#cdd6f4'
     searchingActiveBorderColor:
       - '#f9e2af'

   authorColors:
     '*': '#b4befe'

# # Gruvbox Dark
# gui:
#   theme:
#     activeBorderColor:
#       - '#fabd2f'   # yellow - active panels
#       - bold
#     inactiveBorderColor:
#       - '#665c54'   # dark gray - inactive panels
#     optionsTextColor:
#       - '#83a598'   # blue - options text
#     selectedLineBgColor:
#       - '#3c3836'   # medium-dark gray - selected line
#     cherryPickedCommitBgColor:
#       - '#504945'   # slightly lighter gray
#     cherryPickedCommitFgColor:
#       - '#ebdbb2'   # light beige - text on cherry-picked bg
#     unstagedChangesColor:
#       - '#fb4934'   # red - clear warning color
#     defaultFgColor:
#       - '#ebdbb2'   # Gruvbox fg (high contrast on dark bg)
#     searchingActiveBorderColor:
#       - '#b8bb26'   # green - draws attention when searching

#   authorColors:
#     '*': '#d3869b'  # purple - for authors


# Tokyo Night Storm
# gui:
#   theme:
#     activeBorderColor:
#       - '#7aa2f7'        # Blue (Active)
#       - bold
#     inactiveBorderColor:
#       - '#565f89'        # Dim gray (Inactive)
#     optionsTextColor:
#       - '#7dcfff'        # Cyan (Options)
#     selectedLineBgColor:
#       - '#292e42'        # Dark background highlight
#     cherryPickedCommitBgColor:
#       - '#3b4261'        # Subtle dark bg
#     cherryPickedCommitFgColor:
#       - '#f7768e'        # Red (emphasis)
#     unstagedChangesColor:
#       - '#f7768e'        # Red (unstaged)
#     defaultFgColor:
#       - '#c0caf5'        # Default foreground
#     searchingActiveBorderColor:
#       - '#e0af68'        # Yellow (search highlight)

#   authorColors:
#     '*': '#bb9af7'       # Magenta (author names)


# Ayu Mirage
# gui:
#   theme:
#     activeBorderColor:
#       - '#FFD173'
#       - bold
#     inactiveBorderColor:
#       - '#B8CFE6'
#     optionsTextColor:
#       - '#FFDFB3'
#     selectedLineBgColor:
#       - '#637599'
#     cherryPickedCommitBgColor:
#       - '#B8CFE6'
#     cherryPickedCommitFgColor:
#       - '#FFD173'
#     unstagedChangesColor:
#       - '#95E6CB'
#     defaultFgColor:
#       - '#CCCAC2'
#     searchingActiveBorderColor:
#       - '#F28779'
#   authorColors:
#     '*': '#80BFFF'

# Ashen Theme
# Author: Daniel Fichtinger
# License: MIT
# gui:
#   authorColors:
#     # Recommended: Set your own name to this color!
#     # "Daniel Fichtinger": "#E49A44"
#     "*": "#B14242"
#   theme:
#     # Border color of focused window
#     activeBorderColor:
#       - "#B14242"

#     # Border color of non-focused windows
#     inactiveBorderColor:
#       - "#a7a7a7"

#     # Border color of focused window when searching in that window
#     searchingActiveBorderColor:
#       - "#4A8B8B"
#       - bold

#     # Color of keybindings help text in the bottom line
#     optionsTextColor:
#       - "#B14242"

#     # Background color of selected line.
#     # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
#     selectedLineBgColor:
#       - "#323232"

#     # Background color of selected line when view doesn't have focus.
#     inactiveViewSelectedLineBgColor:
#       - bold

#     # Foreground color of copied commit
#     cherryPickedCommitFgColor:
#       - "#191919"

#     # Background color of copied commit
#     cherryPickedCommitBgColor:
#       - "#4A8B8B"

#     # Foreground color of marked base commit (for rebase)
#     markedBaseCommitFgColor:
#       - "#d5d5d5"

#     # Background color of marked base commit (for rebase)
#     markedBaseCommitBgColor:
#       - "#191919"

#     # Color for file with unstaged changes
#     unstagedChangesColor:
#       - "#B14242"

#     # Default text color
#     defaultFgColor:
#       - "#d5d5d5"

# vscode dark
# gui:
#   theme:
#     activeBorderColor:
#       - '#7E9CD8'          # Blue for active borders (Light Blue)
#       - bold
#     inactiveBorderColor:
#       - '#6B85A0'          # Muted Blue for inactive borders
#     optionsTextColor:
#       - '#7AA89F'          # Cyan for help text (Commands)
#     selectedLineBgColor:
#       - '#2D4F67'          # Muted Blue (Selection)
#     cherryPickedCommitBgColor:
#       - '#957FB8'          # Soft Purple (Cherry-picked commits)
#     cherryPickedCommitFgColor:
#       - '#DCD7BA'          # Foreground (Soft Beige)
#     unstagedChangesColor:
#       - '#C34043'          # Muted Red (Unstaged Changes)
#     defaultFgColor:
#       - '#DCD7BA'          # Foreground color (Soft Beige)
#     searchingActiveBorderColor:
#       - '#FF9E64'          # Bright Orange for search borders
#   authorColors:
#     '*': '#76946A'          # Subtle Green (Authors)

# GitHub Dark Dimmed (Readable Borders)

# gui:
#   theme:
#     activeBorderColor:
#       - '#cdd9e5'        # scale.gray.0 — lightest gray for max contrast
#       - bold
#     inactiveBorderColor:
#       - '#768390'        # fg.muted — softer but still visible
#     optionsTextColor:
#       - '#6cb6ff'        # scale.blue.2
#     selectedLineBgColor:
#       - '#2d333b'        # canvas.subtle
#     cherryPickedCommitBgColor:
#       - '#444c56'        # border.default
#     cherryPickedCommitFgColor:
#       - '#adbac7'        # fg.default
#     unstagedChangesColor:
#       - '#e5534b'        # danger.fg
#     defaultFgColor:
#       - '#adbac7'        # fg.default
#     searchingActiveBorderColor:
#       - '#c69026'        # attention.fg

#   authorColors:
#     '*': '#6cb6ff'        # scale.blue.2

# gui:
#   theme:
#     activeBorderColor:
#       - '#79c0ff'        # scale.blue.2 — bright blue for active border
#       - bold
#     inactiveBorderColor:
#       - '#484f58'        # scale.gray.5 — darker gray for inactive border
#     optionsTextColor:
#       - '#79c0ff'        # scale.blue.2
#     selectedLineBgColor:
#       - '#161b22'        # canvas.subtle
#     cherryPickedCommitBgColor:
#       - '#30363d'        # border.default
#     cherryPickedCommitFgColor:
#       - '#c9d1d9'        # fg.default
#     unstagedChangesColor:
#       - '#f85149'        # danger.fg
#     defaultFgColor:
#       - '#c9d1d9'        # fg.default
#     searchingActiveBorderColor:
#       - '#d29922'        # attention.fg

#   authorColors:
#     '*': '#79c0ff'        # scale.blue.2

# Kanagawa Theme
# gui:
#   theme:
#     activeBorderColor:
#       - '#DCA561'   # AutumnYellow - warm highlight
#       - bold
#     inactiveBorderColor:
#       - '#54546D'   # Dark muted purple/gray from Kanagawa
#     optionsTextColor:
#       - '#7FB4CA'   # SpringBlue - gentle but visible
#     selectedLineBgColor:
#       - '#2A2A37'   # SumiInk1 - selection background
#     cherryPickedCommitBgColor:
#       - '#3A3A4D'   # Deeper gray, distinguishable
#     cherryPickedCommitFgColor:
#       - '#DCD7BA'   # FujiWhite - soft foreground
#     unstagedChangesColor:
#       - '#E46876'   # WaveRed - clear alert color
#     defaultFgColor:
#       - '#DCD7BA'   # FujiWhite - base foreground
#     searchingActiveBorderColor:
#       - '#98BB6C'   # SpringGreen - active search border

#   authorColors:
#     '*': '#D27E99'  # SakuraPink - subtle and elegant
