# inherits = "kanagawa"
# inherits = "ayu_mirage"
# inherits = "dark_plus"
# inherits = "catppuccin_mocha"
inherits = "ashen"

"ui.background" = {}

# kanagawa edits
# "ui.linenr" = { fg = "dragonBlack6" }
# "ui.gutter" = { fg = "sumiInk6" }
# "keyword" = { fg = "oniViolet"}
# "variable.builtin" = { fg = "waveRed", modifiers = ["italic"] }

# dark plus edits
# "comment" = { fg = "dark_gray" }
# "ui.statusline.insert" = { fg = "dark_gray2", bg = "pale_green" }
