# inherits = "kanagawa"
# inherits = "gruvbox-material"
# inherits = "dark_plus"
inherits = "catppuccin_mocha"
# inherits = "ashen"
# inherits = "github_dark_dimmed"
# inherits = "ayu_mirage"
# inherits = "tokyonight_storm"
# inherits = "github_dark"

"ui.background" = {}
# "ui.virtual.ruler" = {bg ="g_10"}

# kanagawa edits
# "ui.linenr" = { fg = "dragonBlack6" }
# "ui.gutter" = { fg = "sumiInk6" }
# "keyword" = { fg = "oniViolet"}
# "variable.builtin" = { fg = "waveRed", modifiers = ["italic"] }

# dark plus edits
# "comment" = { fg = "dark_gray" }
# "ui.statusline.insert" = { fg = "dark_gray2", bg = "pale_green" }
