# vim:fileencoding=utf-8:foldmethod=marker

# Everforest Dark Medium Palette Reference
# bg:       #2d353b
# fg:       #d3c6aa
# red:      #e67e80
# green:    #a7c080
# yellow:   #dbbc7f
# blue:     #7fbbb3
# aqua:     #83c092
# purple:   #d699b6
# gray:     #4f585e
# dark-gray:#343f44
# selection:#434f55

# : Manager {{{

[mgr]
cwd = { fg = "#7fbbb3" }

hovered         = { reversed = true }
preview_hovered = { underline = true }

find_keyword  = { fg = "#dbbc7f", bold = true, italic = true, underline = true }
find_position = { fg = "#d699b6", bg = "reset", bold = true, italic = true }

symlink_target = { italic = true }

marker_copied   = { fg = "#a7c080", bg = "#a7c080" }
marker_cut      = { fg = "#e67e80", bg = "#e67e80" }
marker_marked   = { fg = "#7fbbb3", bg = "#7fbbb3" }
marker_selected = { fg = "#dbbc7f", bg = "#dbbc7f" }

count_copied   = { fg = "#343f44", bg = "#a7c080" }
count_cut      = { fg = "#343f44", bg = "#e67e80" }
count_selected = { fg = "#343f44", bg = "#dbbc7f" }

border_symbol = "│"
border_style  = { fg = "#4f585e" }

syntect_theme = ""

# : }}}


# : Tabs {{{

[tabs]
active   = { bg = "#7fbbb3", bold = true }
inactive = { fg = "#d3c6aa", bg = "#4f585e" }

sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

# : }}}


# : Mode {{{

[mode]
normal_main = { fg = "#2d353b", bg = "#a7c080", bold = true }
normal_alt  = { fg = "#d3c6aa", bg = "#4f585e", bold = true }

select_main = { fg = "#2d353b", bg = "#e67e80", bold = true }
select_alt  = { fg = "#d3c6aa", bg = "#4f585e", bold = true }

unset_main = { fg = "#2d353b", bg = "#7fbbb3", bold = true }
unset_alt  = { fg = "#d3c6aa", bg = "#4f585e", bold = true }

# : }}}


# : Status bar {{{

[status]
overall   = {}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

permissions_s = { fg = "#2d353b" }
permissions_t = { fg = "#a7c080" }
permissions_r = { fg = "#dbbc7f" }
permissions_w = { fg = "#e67e80" }
permissions_x = { fg = "#7fbbb3" }

progress_label  = { bold = true }
progress_normal = { fg = "#7fbbb3", bg = "#232a2e" }
progress_error  = { fg = "#e67e80", bg = "#232a2e" }

# : }}}


# : Which {{{

[which]
cols            = 3
mask            = { bg = "#2d353b" }
cand            = { fg = "#7fbbb3" }
rest            = { fg = "#4f585e" }
desc            = { fg = "#d699b6" }
separator       = "  "
separator_style = { fg = "#4f585e" }

# : }}}


# : Confirmation {{{

[confirm]
border     = { fg = "#7fbbb3" }
title      = { fg = "#7fbbb3" }
body       = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# : }}}


# : Spotter {{{

[spot]
border = { fg = "#7fbbb3" }
title  = { fg = "#7fbbb3" }

tbl_col  = { fg = "#7fbbb3" }
tbl_cell = { fg = "#dbbc7f", reversed = true }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#a7c080" }
title_warn  = { fg = "#dbbc7f" }
title_error = { fg = "#e67e80" }

icon_info  = ""
icon_warn  = ""
icon_error = ""

# : }}}


# : Picker {{{

[pick]
border   = { fg = "#7fbbb3" }
active   = { fg = "#d699b6", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#7fbbb3" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border   = { fg = "#7fbbb3" }
active   = { reversed = true }
inactive = {}

icon_file    = ""
icon_folder  = ""
icon_command = ""

# : }}}


# : Task manager {{{

[tasks]
border  = { fg = "#7fbbb3" }
title   = {}
hovered = { fg = "#d699b6", underline = true }

# : }}}


# : Help menu {{{

[help]
on      = { fg = "#7fbbb3" }
run     = { fg = "#d699b6" }
desc    = {}
hovered = { reversed = true, bold = true }
footer  = { fg = "#2d353b", bg = "#d3c6aa" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	{ mime = "image/*", fg = "#7fbbb3" },
	{ mime = "{audio,video}/*", fg = "#d699b6" },
	{ mime = "application/*zip", fg = "#e67e80" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#e67e80" },
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7fbbb3" },
	{ name = "*", fg = "#83c092" },
	{ name = "*/", fg = "#a7c080" }
]

# : }}}
